# fly.toml app configuration file generated for fwd-vocoder-discord-bot on 2025-12-15T13:16:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fwd-vocoder-discord-bot'
primary_region = 'fra'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
